export const data = {
  nodes: [
    {
      id: '1',
      name: 'Router 1',
      type: 'router',
      x: 100,
      y: 150,
      connections: [
        { to: '2', type: 'ethernet', status: 'active' },
        { to: '3', type: 'ethernet', status: 'active' },
      ],
    },
    {
      id: '2',
      name: 'Switch 1',
      type: 'switch',
      x: 300,
      y: 250,
      connections: [{ to: '4', type: 'ethernet', status: 'inactive' }],
    },
    {
      id: '3',
      name: 'Server 1',
      type: 'server',
      x: 500,
      y: 300,
      connections: [{ to: '5', type: 'ethernet', status: 'active' }],
    },
    {
      id: '4',
      name: 'Switch 2',
      type: 'switch',
      x: 400,
      y: 500,
      connections: [{ to: '6', type: 'ethernet', status: 'inactive' }],
    },
    {
      id: '5',
      name: 'Server 2',
      type: 'server',
      x: 200,
      y: 450,
      connections: [{ to: '7', type: 'ethernet', status: 'active' }],
    },
    {
      id: '6',
      name: 'Client Device 1',
      type: 'client',
      x: 700,
      y: 200,
      connections: [],
    },
    {
      id: '7',
      name: 'Router 2',
      type: 'router',
      x: 900,
      y: 150,
      connections: [
        { to: '8', type: 'ethernet', status: 'active' },
        { to: '9', type: 'ethernet', status: 'inactive' },
      ],
    },
    {
      id: '8',
      name: 'Switch 3',
      type: 'switch',
      x: 1000,
      y: 400,
      connections: [{ to: '10', type: 'ethernet', status: 'active' }],
    },
    {
      id: '9',
      name: 'Server 3',
      type: 'server',
      x: 1100,
      y: 600,
      connections: [],
    },
    {
      id: '10',
      name: 'Client Device 2',
      type: 'client',
      x: 200,
      y: 700,
      connections: [{ to: '11', type: 'wifi', status: 'inactive' }],
    },
    {
      id: '11',
      name: 'Router 3',
      type: 'router',
      x: 250,
      y: 150,
      connections: [{ to: '12', type: 'ethernet', status: 'active' }],
    },
    {
      id: '12',
      name: 'Switch 4',
      type: 'switch',
      x: 350,
      y: 200,
      connections: [{ to: '13', type: 'ethernet', status: 'active' }],
    },
    {
      id: '13',
      name: 'Server 4',
      type: 'server',
      x: 450,
      y: 300,
      connections: [{ to: '14', type: 'ethernet', status: 'active' }],
    },
    {
      id: '14',
      name: 'Switch 5',
      type: 'switch',
      x: 550,
      y: 350,
      connections: [],
    },

    {
      id: '16',
      name: 'Server 5',
      type: 'server',
      x: 750,
      y: 500,
      connections: [],
    },
    {
      id: '17',
      name: 'Client Device 3',
      type: 'client',
      x: 850,
      y: 600,
      connections: [{ to: '18', type: 'wifi', status: 'active' }],
    },
    {
      id: '18',
      name: 'Router 5',
      type: 'router',
      x: 100,
      y: 650,
      connections: [{ to: '19', type: 'ethernet', status: 'active' }],
    },
    {
      id: '19',
      name: 'Switch 6',
      type: 'switch',
      x: 1100,
      y: 200,
      connections: [{ to: '20', type: 'ethernet', status: 'active' }],
    },
    {
      id: '20',
      name: 'Server 6',
      type: 'server',
      x: 1000,
      y: 500,
      connections: [],
    },
    {
      id: '24',
      name: 'Server 7',
      type: 'server',
      x: 300,
      y: 400,
      connections: [{ to: '25', type: 'ethernet', status: 'inactive' }],
    },
    {
      id: '25',
      name: 'Client Device 5',
      type: 'client',
      x: 400,
      y: 600,
      connections: [],
    },
  ],
};
